In [1]:
import numpy as np

In [7]:
# array from 0 to 20

my_arr = np.arange(0,21,2)

my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
# use brackets to get a value at an index
# NOT position

my_arr[4]

8

In [9]:
# grab a slice
# remember indexing starts at zero

my_arr[1:4]

array([2, 4, 6])

In [15]:
# everything from the beginning to a specified point
# the end point is NOT inclusive
# the number 12 is at index 6

my_arr[:7]

array([ 0,  2,  4,  6,  8, 10, 12])

In [16]:
# everything from a given index to the end of the array

my_arr[3:]

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
# understanding indexing might be easier with string inputs

arr = np.array(['a','b','c','d','e','f','g'])

arr

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='<U1')

In [25]:
arr[3]

'd'

In [26]:
arr[3:6]

array(['d', 'e', 'f'], dtype='<U1')

In [27]:
arr[:5]

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [28]:
arr = np.array(['one','two','three','four','five','six','seven','eight','nine','ten'])

arr

array(['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight',
       'nine', 'ten'], dtype='<U5')

In [29]:
arr[4]

'five'

In [30]:
arr[7]

'eight'

In [32]:
# remember, the end point is not inclusive

arr[2:6]

array(['three', 'four', 'five', 'six'], dtype='<U5')

In [37]:
# this one will match string-number to index because
# the beginning index is zero, and numpy arrays, like python lists
# are zero-indexed and non-inclusive at the high end :)
# this will return up to index 4

arr[:5]

array(['one', 'two', 'three', 'four', 'five'], dtype='<U5')

In [38]:
arr[5:]

array(['six', 'seven', 'eight', 'nine', 'ten'], dtype='<U5')