In [1]:
import numpy as np

In [7]:
# array from 0 to 20

my_arr = np.arange(0,21,2)

my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
# use brackets to get a value at an index
# NOT position

my_arr[4]

8

In [9]:
# grab a slice
# remember indexing starts at zero

my_arr[1:4]

array([2, 4, 6])

In [15]:
# everything from the beginning to a specified point
# the end point is NOT inclusive
# the number 12 is at index 6

my_arr[:7]

array([ 0,  2,  4,  6,  8, 10, 12])

In [16]:
# everything from a given index to the end of the array

my_arr[3:]

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
# understanding indexing might be easier with string inputs

arr = np.array(['a','b','c','d','e','f','g'])

arr

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='<U1')

In [25]:
arr[3]

'd'

In [26]:
arr[3:6]

array(['d', 'e', 'f'], dtype='<U1')

In [27]:
arr[:5]

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [28]:
arr = np.array(['one','two','three','four','five','six','seven','eight','nine','ten'])

arr

array(['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight',
       'nine', 'ten'], dtype='<U5')

In [29]:
arr[4]

'five'

In [30]:
arr[7]

'eight'

In [32]:
# remember, the end point is not inclusive

arr[2:6]

array(['three', 'four', 'five', 'six'], dtype='<U5')

In [37]:
# this one will match string-number to index because
# the beginning index is zero, and numpy arrays, like python lists
# are zero-indexed and non-inclusive at the high end :)
# this will return up to index 4

arr[:5]

array(['one', 'two', 'three', 'four', 'five'], dtype='<U5')

In [38]:
arr[5:]

array(['six', 'seven', 'eight', 'nine', 'ten'], dtype='<U5')

In [39]:
# all in all, these are basically  the same as python lists
# why is numpy different? 
# broadcasting.

In [40]:
# broadcast a new value to a subset of an array using numpy
# remember my_arr?

my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
# broadcasting:

my_arr[3:7] = 69
my_arr

array([ 0,  2,  4, 69, 69, 69, 69, 14, 16, 18, 20])

In [43]:
# slicing + braodcasting: DANGER ZONE

new_arr = np.arange(0,20,2)

new_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
sliced_new_arr = new_arr[:4]

sliced_new_arr

array([0, 2, 4, 6])

In [45]:
# now to broadcast--BEWARE

sliced_new_arr[:] = 69

sliced_new_arr

array([69, 69, 69, 69])

In [46]:
# oh noes, it didn't just change the slice, it affected the original array!

new_arr

array([69, 69, 69, 69,  8, 10, 12, 14, 16, 18])

In [47]:
# so what this means is that data isn't copied when they slice
# numpy does this to avoid issues wiith very large arrays
# have to deliberately set copies to do that
# slices aren't copies, just windows into whatever section of the array you specify

In [50]:
# how to set up a copy
# make a copy, label it so you know what it is, then work on that
# use .copy()

new_arr_copy = new_arr.copy()
new_arr_copy

array([69, 69, 69, 69,  8, 10, 12, 14, 16, 18])

In [51]:
# now broadcasting to the COPY

new_arr_copy[:] = 101

new_arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [53]:
# cool. let's check the original new_arr
# should be untouched with the 69s still there

new_arr

array([69, 69, 69, 69,  8, 10, 12, 14, 16, 18])