## preprocessing with scikit-learn

this notebook is intended to be a reference for using scikit learn in preprocessing

In [2]:
import numpy as np

from sklearn.preprocessing import MinMaxScaler

In [14]:
# this will give a 5x3 matrix with random integers from 0 to 199

dataset = np.random.randint(0,200,(5,3))

In [21]:
dataset

array([[113, 155,  27],
       [ 24, 161, 188],
       [ 90, 178, 138],
       [ 53,  98,  98],
       [ 83, 102, 116]])

In [25]:
# scale data: instatiate a MinMaxScaler object
my_scaler = MinMaxScaler()

type(my_scaler)

sklearn.preprocessing.data.MinMaxScaler

In [26]:
# fit to the data
# scikit-learn follows conventions like data.fit()

my_scaler.fit(dataset)

/home/susanna/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [27]:
# transform the data

my_scaler.transform(dataset)

array([[1.        , 0.7125    , 0.        ],
       [0.        , 0.7875    , 1.        ],
       [0.74157303, 1.        , 0.68944099],
       [0.3258427 , 0.        , 0.44099379],
       [0.66292135, 0.05      , 0.55279503]])

data are transformed such that the minimum value becomes zero (0) and the max value becomes one (1).
#### * there are other ways to normalize data, but this one is pretty solid for many machine learning purposes
#### * this can actually be done i one command, using the MinMaxScaler fit_transform() method:

In [29]:
# one line, same results using fit_transform() method

my_scaler.fit_transform(dataset)

/home/susanna/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[1.        , 0.7125    , 0.        ],
       [0.        , 0.7875    , 1.        ],
       [0.74157303, 1.        , 0.68944099],
       [0.3258427 , 0.        , 0.44099379],
       [0.66292135, 0.05      , 0.55279503]])