In [2]:
import tensorflow as tf

# tensors
### tensors are n-dimensional arrays

In [23]:
hello_const = tf.constant('hello ')

In [24]:
# shows that it's a tensor type

type(hello_const)

tensorflow.python.framework.ops.Tensor

In [32]:
world_const = tf.constant('world!')

type(world_const)

tensorflow.python.framework.ops.Tensor

### sessions

tensorflow won't just run operations. first you have to initialize a session, then set up the operation, then run. observe:

In [26]:
# can't just add them together to output a result:

hello_world = hello_const + world_const

# instead of the result, this will give information on the request
hello_world

<tf.Tensor 'add_6:0' shape=() dtype=string>

In [27]:
# what type is hello_world? a tensor:

type(hello_world)

tensorflow.python.framework.ops.Tensor

now the right way: run it in a session using 'with' keyword

In [30]:
# set up the session
# then run it

with tf.Session() as sess:
    hello_world = sess.run(hello_const + world_const)

In [33]:
# get the result

hello_world

b'hello world!'

the session-run-rule also applies to integer constants:

In [36]:
# these are tensors, just like above

const_1 = tf.constant(1)
const_2 = tf.constant(2)

# see?
print(type(const_1))
print(type(const_2))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [38]:
const_1 + const_2

<tf.Tensor 'add_10:0' shape=() dtype=int32>

In [39]:
add_result = const_1 + const_2

add_result

<tf.Tensor 'add_11:0' shape=() dtype=int32>

In [41]:
# set up a session, run the computation

with tf.Session() as sess:
    sess_add = sess.run(add_result)

In [44]:
# it works!

sess_add

3

#### other operations

let's create and run some matrices using this tensorflow session:

In [47]:
# tensorflow has a number of methods to create matrices
# as always shift + tab to see options

# arguments here: dimensions (5x5), fill number (10s)
matrix_10s = tf.fill((5,5),10)

# similar to numpy zeros(), pass dimensions in as a tuple
matrix_0s = tf.zeros((5,5))

# similar to numpy ones(), pass dimensions in as a tuple
matrix_1s = tf.ones((5,5))

# draws from random normal distribution
# specify dimensions as tuple, mean & stddev (values here are defaults, for example purposes)
matrix_rand_nrml = tf.random_normal((5,5), mean=0, stddev=1.0)

# draws from random uniform distribution, specify min value & max value
matrix_rand_uni = tf.random_uniform((5,5), minval=0, maxval=1)

# although values have been assigned (ie nodes designated)
# executing this window won't do anything visible

In [49]:
# again, this only displays types--not results
# these are tensors of shape 5x5

print(matrix_10s, matrix_0s, matrix_1s, matrix_rand_nrml, matrix_rand_uni)

Tensor("Fill_2:0", shape=(5, 5), dtype=int32) Tensor("zeros_1:0", shape=(5, 5), dtype=float32) Tensor("ones_1:0", shape=(5, 5), dtype=float32) Tensor("random_normal_1:0", shape=(5, 5), dtype=float32) Tensor("random_uniform_1:0", shape=(5, 5), dtype=float32)


now let's run these operations (in a session) to actually create these matrices:

In [58]:
matrices = [matrix_10s, matrix_0s, matrix_1s, matrix_rand_nrml, matrix_rand_uni]

with tf.Session() as sess:
    for matrix in matrices:
        matrix = sess.run(matrix)
        print(matrix, '\n')
        
# could also have used: print(sess.run(matrix), '\n')
# written this way for clarity

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[-1.4953055  -0.02974314  0.21285395  0.7526569  -0.19957118]
 [-2.0818648  -1.466015   -0.21336704 -0.47112435 -0.9460184 ]
 [ 1.422221   -1.3705472   0.24465986  1.1819116  -1.0084287 ]
 [ 0.7728608  -0.41386327 -0.19681427  0.5536151  -0.8584271 ]
 [-1.6168275  -1.1169975   0.76580685 -0.13801475 -0.03801071]] 

[[0.50554    0.3025005  0.35884655 0.6664016  0.30117214]
 [0.04736674 0.28699362 0.6510503  0.7422918  0.19725108]
 [0.5796169  0.8883376  0.8934052  0.04474401 0.24305785]
 [0.00198519 0.08063889 0.13913214 0.62264407 0.41798925]
 [0.111202   0.27060628 0.9137343  0.12376583 0.16896546]] 



### for notebooks only: interactive sessions

(demo/exploratory only, not production!)

In [69]:
# initialize an interactive session once:

sess = tf.InteractiveSession()

In [70]:
# run the matrix operations again
# this time don't need to set up a session

for matrix in matrices:
    print(sess.run(matrix), '\n')

# could have also used: print(matrix.eval(), '\n')

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[ 0.30078822 -0.3652641  -1.5013678  -0.57419926 -2.4534965 ]
 [-1.3006604  -3.1587548  -2.0857582  -0.6759294  -0.98026705]
 [ 3.0593398   2.0785499  -0.13183726  1.2449057   1.6237723 ]
 [-0.41720775 -1.2550651  -0.9903041  -0.3700718   0.35372376]
 [-1.0963378   0.280933    0.9090837   0.10284939  2.098315  ]] 

[[0.25819778 0.25928283 0.08141637 0.21233153 0.5674292 ]
 [0.894876   0.40571105 0.8185481  0.90550935 0.81330264]
 [0.6329787  0.777809   0.4340359  0.02841759 0.13754964]
 [0.52275395 0.6642351  0.60434556 0.386922   0.68181217]
 [0.46332812 0.8321761  0.9226556  0.68266404 0.7311609 ]] 



In [71]:
sess.close()

### matrix multiplication

In [82]:
matrix_A = tf.constant([[5,10,],
                        [15,20]])

matrix_B = tf.constant([[25,30,35],
                        [40,45,50]])

In [85]:
# matrix_A is a 2x2 matrix

matrix_A.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_19:0' shape=(2, 2) dtype=int32>>

In [86]:
# matrix_B is a 2x3 matrix

matrix_B.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_20:0' shape=(2, 3) dtype=int32>>

In [91]:
# set up what we want to do, assing the operation to a variable
# tf.matmul() does matrix multiplication (duh)

mat_multiply = tf.matmul(matrix_A, matrix_B)

In [92]:
type(mat_multiply)

tensorflow.python.framework.ops.Tensor

now to run it in a session:

In [98]:
# set up the session
# remember we closed our interactive session from earlier

with tf.Session() as sess:
    print(sess.run(mat_multiply))

[[ 525  600  675]
 [1175 1350 1525]]


In [100]:
# note: could also use .eval() here too

with tf.Session() as sess:
    print(mat_multiply.eval())

[[ 525  600  675]
 [1175 1350 1525]]


## graphs in tensorflow

In [104]:
node_1 = tf.constant(1)

node_2 = tf.constant(2)

node_3 = node_1 + node_2

with tf.Session() as sess:
    add_nodes = sess.run(node_3)

print(add_nodes)

3


reminder: simply calling node_3 won't run it; it had to be run in a session (as above). calling node_3 just returns the type:

In [106]:
print(node_3)

Tensor("add_14:0", shape=(), dtype=int32)


#### default graphs

In [108]:
# shows graph object type & location in memory

print(tf.get_default_graph())

In [113]:
# make a new graph

second_graph = tf.Graph()

# will show a different graph object (different memory location)

print(second_graph)

resetting the default graph:

In [114]:
# set the current default graph to a variable:

first_graph = tf.get_default_graph()

# check to see: first_graph IS the original default graph
# same memory location: 0x7f07cd5117b8

print(first_graph)

In [116]:
# mae a 3rd graph (order: default/first, second, third)

third_graph = tf.Graph()

print(third_graph)

In [119]:
# set second_graph to run as the default using .as_default()

with second_graph.as_default():
    
    # use 'is' to check if second_graph is the default, will return True if it is
    print(second_graph is tf.get_default_graph())

True


but this doesn't make second_graph the default! it's only *running as* the default in the current session. here's what happens using the 'is' keyword to check whether second_graph is the default *outside* of the session:

In [120]:
print(second_graph is tf.get_default_graph())

False


it's false, because outside of that session second_graph is not the default; first_graph still is:

In [121]:
print(tf.get_default_graph())

note the memory location: 0x7f07cd5117b8

the default graph is still the original default graph, aka first_graph, outside the session where we ran second_graph as default.