In [2]:
import tensorflow as tf

# tensors
### tensors are n-dimensional arrays

In [23]:
hello_const = tf.constant('hello ')

In [24]:
# shows that it's a tensor type

type(hello_const)

tensorflow.python.framework.ops.Tensor

In [32]:
world_const = tf.constant('world!')

type(world_const)

tensorflow.python.framework.ops.Tensor

#### sessions

tensorflow won't just run operations. first you have to initialize a session, then set up the operation, then run. observe:

In [26]:
# can't just add them together to output a result:

hello_world = hello_const + world_const

# instead of the result, this will give information on the request
hello_world

<tf.Tensor 'add_6:0' shape=() dtype=string>

In [27]:
# what type is hello_world? a tensor:

type(hello_world)

tensorflow.python.framework.ops.Tensor

now the right way: run it in a session using 'with' keyword

In [30]:
# set up the session
# then run it

with tf.Session() as sess:
    hello_world = sess.run(hello_const + world_const)

In [33]:
# get the result

hello_world

b'hello world!'

the session-run-rule also applies to integer constants:

In [36]:
# these are tensors, just like above

const_1 = tf.constant(1)
const_2 = tf.constant(2)

# see?
print(type(const_1))
print(type(const_2))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [38]:
const_1 + const_2

<tf.Tensor 'add_10:0' shape=() dtype=int32>

In [39]:
add_result = const_1 + const_2

add_result

<tf.Tensor 'add_11:0' shape=() dtype=int32>

In [41]:
# set up a session, run the computation

with tf.Session() as sess:
    sess_add = sess.run(add_result)

In [44]:
# it works!

sess_add

3

#### other operations

let's create and run some matrices using this tensorflow session:

In [47]:
# tensorflow has a number of methods to create matrices
# as always shift + tab to see options

# arguments here: dimensions (5x5), fill number (10s)
matrix_10s = tf.fill((5,5),10)

# similar to numpy zeros(), pass dimensions in as a tuple
matrix_0s = tf.zeros((5,5))

# similar to numpy ones(), pass dimensions in as a tuple
matrix_1s = tf.ones((5,5))

# draws from random normal distribution
# specify dimensions as tuple, mean & stddev (values here are defaults, for example purposes)
matrix_rand_nrml = tf.random_normal((5,5), mean=0, stddev=1.0)

# draws from random uniform distribution, specify min value & max value
matrix_rand_uni = tf.random_uniform((5,5), minval=0, maxval=1)

# although values have been assigned (ie nodes designated)
# executing this window won't do anything visible

In [49]:
# again, this only displays types--not results
# these are tensors of shape 5x5

print(matrix_10s, matrix_0s, matrix_1s, matrix_rand_nrml, matrix_rand_uni)

Tensor("Fill_2:0", shape=(5, 5), dtype=int32) Tensor("zeros_1:0", shape=(5, 5), dtype=float32) Tensor("ones_1:0", shape=(5, 5), dtype=float32) Tensor("random_normal_1:0", shape=(5, 5), dtype=float32) Tensor("random_uniform_1:0", shape=(5, 5), dtype=float32)


now let's run these operations (in a session) to actually create these matrices:

In [53]:
matrices = [matrix_10s, matrix_0s, matrix_1s, matrix_rand_nrml, matrix_rand_uni]

with tf.Session() as sess:
    for matrix in matrices:
        matrix = sess.run(matrix)
        print(matrix, '\n')

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[-1.1376288  -0.8223175  -0.7536955  -0.5834289  -0.73217523]
 [ 0.49167112  0.04779798 -0.16006713  0.5670915  -0.69069713]
 [-1.437848    2.0215385   1.5232288   0.4442079  -1.5998803 ]
 [ 0.09378536  0.15062259  0.8032139   0.59091103  2.928433  ]
 [-1.1760981   1.2564436   0.69118     0.75585854 -2.6854546 ]] 

[[0.385033   0.41825306 0.08613026 0.40889204 0.17649806]
 [0.02539563 0.9244497  0.54020834 0.33388996 0.31073844]
 [0.26666188 0.25108135 0.07042992 0.6984509  0.3433448 ]
 [0.08534086 0.03742158 0.3902731  0.49277222 0.37603378]
 [0.2236427  0.24113894 0.29635704 0.6823164  0.35546303]] 

