In [2]:
import tensorflow as tf

# tensors
### tensors are n-dimensional arrays

In [23]:
hello_const = tf.constant('hello ')

In [24]:
# shows that it's a tensor type

type(hello_const)

tensorflow.python.framework.ops.Tensor

In [32]:
world_const = tf.constant('world!')

type(world_const)

tensorflow.python.framework.ops.Tensor

### sessions

tensorflow won't just run operations. first you have to initialize a session, then set up the operation, then run. observe:

In [26]:
# can't just add them together to output a result:

hello_world = hello_const + world_const

# instead of the result, this will give information on the request
hello_world

<tf.Tensor 'add_6:0' shape=() dtype=string>

In [27]:
# what type is hello_world? a tensor:

type(hello_world)

tensorflow.python.framework.ops.Tensor

now the right way: run it in a session using 'with' keyword

In [30]:
# set up the session
# then run it

with tf.Session() as sess:
    hello_world = sess.run(hello_const + world_const)

In [33]:
# get the result

hello_world

b'hello world!'

the session-run-rule also applies to integer constants:

In [36]:
# these are tensors, just like above

const_1 = tf.constant(1)
const_2 = tf.constant(2)

# see?
print(type(const_1))
print(type(const_2))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [38]:
const_1 + const_2

<tf.Tensor 'add_10:0' shape=() dtype=int32>

In [39]:
add_result = const_1 + const_2

add_result

<tf.Tensor 'add_11:0' shape=() dtype=int32>

In [41]:
# set up a session, run the computation

with tf.Session() as sess:
    sess_add = sess.run(add_result)

In [44]:
# it works!

sess_add

3

#### other operations

let's create and run some matrices using this tensorflow session:

In [47]:
# tensorflow has a number of methods to create matrices
# as always shift + tab to see options

# arguments here: dimensions (5x5), fill number (10s)
matrix_10s = tf.fill((5,5),10)

# similar to numpy zeros(), pass dimensions in as a tuple
matrix_0s = tf.zeros((5,5))

# similar to numpy ones(), pass dimensions in as a tuple
matrix_1s = tf.ones((5,5))

# draws from random normal distribution
# specify dimensions as tuple, mean & stddev (values here are defaults, for example purposes)
matrix_rand_nrml = tf.random_normal((5,5), mean=0, stddev=1.0)

# draws from random uniform distribution, specify min value & max value
matrix_rand_uni = tf.random_uniform((5,5), minval=0, maxval=1)

# although values have been assigned (ie nodes designated)
# executing this window won't do anything visible

In [49]:
# again, this only displays types--not results
# these are tensors of shape 5x5

print(matrix_10s, matrix_0s, matrix_1s, matrix_rand_nrml, matrix_rand_uni)

Tensor("Fill_2:0", shape=(5, 5), dtype=int32) Tensor("zeros_1:0", shape=(5, 5), dtype=float32) Tensor("ones_1:0", shape=(5, 5), dtype=float32) Tensor("random_normal_1:0", shape=(5, 5), dtype=float32) Tensor("random_uniform_1:0", shape=(5, 5), dtype=float32)


now let's run these operations (in a session) to actually create these matrices:

In [58]:
matrices = [matrix_10s, matrix_0s, matrix_1s, matrix_rand_nrml, matrix_rand_uni]

with tf.Session() as sess:
    for matrix in matrices:
        matrix = sess.run(matrix)
        print(matrix, '\n')
        
# could also have used: print(sess.run(matrix), '\n')
# written this way for clarity

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[-1.4953055  -0.02974314  0.21285395  0.7526569  -0.19957118]
 [-2.0818648  -1.466015   -0.21336704 -0.47112435 -0.9460184 ]
 [ 1.422221   -1.3705472   0.24465986  1.1819116  -1.0084287 ]
 [ 0.7728608  -0.41386327 -0.19681427  0.5536151  -0.8584271 ]
 [-1.6168275  -1.1169975   0.76580685 -0.13801475 -0.03801071]] 

[[0.50554    0.3025005  0.35884655 0.6664016  0.30117214]
 [0.04736674 0.28699362 0.6510503  0.7422918  0.19725108]
 [0.5796169  0.8883376  0.8934052  0.04474401 0.24305785]
 [0.00198519 0.08063889 0.13913214 0.62264407 0.41798925]
 [0.111202   0.27060628 0.9137343  0.12376583 0.16896546]] 



### for notebooks only: interactive sessions

(demo/exploratory only, not production!)

In [59]:
# initialize an interactive session once:

sess = tf.InteractiveSession()

In [61]:
# run the matrix operations again
# this time don't need to set up a session

for matrix in matrices:
    print(matrix.eval(), '\n')

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[-0.20615102 -0.96041656  0.37703153  1.8141747  -0.51982003]
 [ 0.65142184 -0.24351689  1.1047015   0.35330847 -0.19969681]
 [-0.5648185  -0.43736267  2.3816383  -0.32069695  0.872908  ]
 [ 1.0472759  -0.57253015  0.7001373   0.542445   -0.86554223]
 [ 0.98741543 -1.0551876   0.3692475   0.12021515 -0.9450938 ]] 

[[0.891768   0.96788776 0.9724809  0.49903226 0.9838047 ]
 [0.35092092 0.05184782 0.31989026 0.8828318  0.706651  ]
 [0.44791424 0.5392283  0.05418563 0.2350533  0.8552202 ]
 [0.55169463 0.40098107 0.91126096 0.16424382 0.18115604]
 [0.07792854 0.41566658 0.22207046 0.9641938  0.89753616]] 



In [62]:
sess.close()